routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('products','ProductController');


// login
Route::get('/login', 'otentikasi\OtentikasiController@index' )-> name('login') ;
Route::post('/login', 'otentikasi\OtentikasiController@login') -> name('login');
Route::get('/logout', 'otentikasi\OtentikasiController@logout') -> name('logout');
//midleware otentikasi
Route::group(['middleware' => 'auth'], function () {
    
    Route::get('/lihatuser', 'otentikasi\OtentikasiController@lihatuser' )-> name('lihat-user') ;
    Route::get('/tambahuser', 'otentikasi\OtentikasiController@tambah' )-> name('tambah-user') ;
    Route::post('/tambahuser/simpan', 'otentikasi\OtentikasiController@simpan') -> name('tambah-user-simpan');
    //profile user
    Route::get('/profile', 'otentikasi\OtentikasiController@profile' )-> name('profile') ;
    Route::post('/profile/simpan', 'otentikasi\OtentikasiController@profilesimpan') -> name('profile-user-simpan');
    //home
    Route::get('/home', function () {    return view('home');    });
    Route::get('/', function () {    return view('home');    });
    Route::post('/bukuinduk/print/{id}', 'bukuindukController@print') -> name('bukuinduk-print');
    Route::resource('parameteruji','parameterujiController');
    Route::resource('bukuinduk','bukuindukController');
    Route::resource('datapelanggan','datapelangganController');
    Route::delete('/userdel/{id}','datapelangganController@destroy')->name('userdel');
    Route::get('/reset/{id}','datapelangganController@resetpass')->name('resetpass');
});

app/Http/Controllers/parameterujiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;


class parameterujiController extends Controller
{
    public function index(){
        $parameter_uji = DB::table('parameter_uji')->orderBy('name','ASC')->get();
        return view('lab_kimia.parameter_uji.index',['parameter_uji' => $parameter_uji]);
        
    }

    public function create(){
         return view('lab_kimia.parameter_uji.tambah-parameter-uji');
        
    }
    

    public function store(Request $request){
        $data_insert[] = array(
            'name' => $request->name,
            'kategori' => $request->kategori,
            'harga' => $request->harga,
        );

        DB::table('parameter_uji')->insert( $data_insert);
        return Redirect()->route('parameteruji.index') -> with('success','berhasil menambah data');
    }

    public function update(Request $request,  $id)
    {
        // dd($request->all(), $id);
        DB::table('parameter_uji')
              ->where('id', $id)
              ->update(['name' => $request->name]);

        return redirect()->route('parameteruji.index')
                        ->with('success','Data berhasil di update');
    }

    public function edit($id)
    {
        $parameter_uji = DB::table('parameter_uji')->where('id',$id)->orderBy('name','ASC')->get();
        return view('lab_kimia.parameter_uji.edit',['parameter_uji' => $parameter_uji]);
    }

    public function destroy($id)

    {
        // dd($id);
        
        DB::table('parameter_uji')->where('id','=', $id)->delete();
        
        return redirect()->route('parameteruji.index') -> with('deleted','berhasil menghapus');
    }
}

resources/views/lab_kimia/parameter_uji/edit.blade.php
@extends('layouts.master')
@section('title', 'Daftar parameter uji')

@section('content')
    <section class="section">
        <div class="section-header">
        
        <h1>Silahkan ubah dan klik simpan atau <a href="{{  route('parameteruji.index')}}" class="btn btn-info">Kembali</a> </h1> 
        </div>
    </section>
    <div class="section-body">
        
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                   
                    @foreach ($parameter_uji  as $no => $item)
                        <form action="{{ route('parameteruji.update',$item->id) }}" method="POST">
                        @method('PUT')
                        <div class="col-md-12">
                            <div class="form-group">
                        <i>* jika ingin memasukan simbol  di atas silahkan ketik dengan menambahkan tag <b> &lt;sup&gt;angka atau hurufnya&lt;sup&gt;</b></i> Cth : H&lt;sup&gt;2&lt;sup&gt;O | Hasil H<sup>2</sup>O<br>
                        <i>* jika ingin memasukan simbol  di bawah silahkan ketik dengan menambahkan tag <b> &lt;sub&gt;angka atau hurufnya&lt;sub&gt; </b> </i> Cth : H&lt;sub&gt;2&lt;sub&gt;O | Hasil H<sub>2</sub>O<br><br>
                        <label for="">Nama Parameter Uji</label><br>
                        <input type="text" value="{{$item->name}}" name="name" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>* Harga</label>
                            <input type="number" value="{{$item->harga}}" placeholder="Masukan Harga hanya dengan angka" name="harga" class="form-control">
                            </div>
                        </div>
                            @csrf
                            <button type="submit" class="btn btn-success">Simpan</button>
                        </form>
                    @endforeach
            </div>

        </div>
    </div>
    </div>
@endsection

@push('page-script')

@endpush

resources/views/lab_kimia/parameter_uji/index.blade.php
@extends('layouts.master')
@section('title', 'Daftar parameter uji')

@section('content')
    <section class="section">
        <div class="section-header">
        
        <h1><a href="{{ route('parameteruji.create') }}" class="btn btn-info">Tambah Data</a>    Parameter uji </h1> 
        </div>
    </section>
    <div class="section-body">
        
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                    @endif
                    @if ($message = Session::get('deleted'))
                    <div class="alert alert-danger">
                        <p>{{ $message }}</p>
                    </div>
                    @endif
                    @foreach ($parameter_uji  as $no => $item)
                <span>{{$no+1  }} . {!!$item->name!!} - Rp. {{number_format($item->harga,0,",",".")}}</span>
                        <form action="{{ route('parameteruji.destroy',$item->id) }}" method="POST">
                            {{-- <a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a> --}}
                            <a class="btn btn-primary" href="{{ route('parameteruji.edit',$item->id) }}">Show</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    @endforeach
            </div>

        </div>
    </div>
    </div>
@endsection

@push('page-script')

@endpush

resources/views/lab_kimia/parameter_uji/tambah-parameter-uji.blade.php
@extends('layouts.master')
@section('title', 'Tambah parameter uji')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Input parameter uji</h1>
        </div>
    </section>
    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">

                    <form action="{{ route('parameteruji.store') }}" method="POST">
                        @csrf
                        
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label >* Kategori Parameter Uji</label>
                                        <select name="kategori" class="form-control" >
                                            <option value="">Silahkan pilih</option>
                                            <option value="1">Physicals Properties</option>
                                            <option value="2">Chemicals Properties</option>
                                            <option value="3">Heavy Metal</option>
                                            <option value="4">Biology Properties</option>
                                            <option value="5">LUMSUM/Hari</option>
                                        </select>
                                    </div>

                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <i>* jika ingin memasukan simbol  di atas silahkan ketik dengan menambahkan tag <b> &lt;sup&gt;angka atau hurufnya&lt;sup&gt;</b></i> Cth : H&lt;sup&gt;2&lt;sup&gt;O | Hasil H<sup>2</sup>O<br>
                                        <i>* jika ingin memasukan simbol  di bawah silahkan ketik dengan menambahkan tag <b> &lt;sub&gt;angka atau hurufnya&lt;sub&gt; </b> </i> Cth : H&lt;sub&gt;2&lt;sub&gt;O | Hasil H<sub>2</sub>O<br><br>
                                        <label>* Nama</label>
                                        <input type="text" placeholder="Masukan Nama Parameter Uji" name="name" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>* Harga</label>
                                        <input type="number" placeholder="Masukan Harga hanya dengan angka" name="harga" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="card-footer text-right">
                                        <button class="btn btn-primary mr-1" type="submit">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                
                </form>
            </div>

        </div>
    </div>
    </div>
@endsection

@push('page-script')

@endpush