routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('products','ProductController');


// login
Route::get('/login', 'otentikasi\OtentikasiController@index' )-> name('login') ;
Route::post('/login', 'otentikasi\OtentikasiController@login') -> name('login');
Route::get('/logout', 'otentikasi\OtentikasiController@logout') -> name('logout');
//midleware otentikasi
Route::group(['middleware' => 'auth'], function () {
    
    Route::get('/lihatuser', 'otentikasi\OtentikasiController@lihatuser' )-> name('lihat-user') ;
    Route::get('/tambahuser', 'otentikasi\OtentikasiController@tambah' )-> name('tambah-user') ;
    Route::post('/tambahuser/simpan', 'otentikasi\OtentikasiController@simpan') -> name('tambah-user-simpan');
    //profile user
    Route::get('/profile', 'otentikasi\OtentikasiController@profile' )-> name('profile') ;
    Route::post('/profile/simpan', 'otentikasi\OtentikasiController@profilesimpan') -> name('profile-user-simpan');
    //home
    Route::get('/home', function () {    return view('home');    });
    Route::get('/', function () {    return view('home');    });
    Route::post('/bukuinduk/print/{id}', 'bukuindukController@print') -> name('bukuinduk-print');
    Route::resource('parameteruji','parameterujiController');
    Route::resource('bukuinduk','bukuindukController');
    Route::resource('datapelanggan','datapelangganController');
    Route::delete('/userdel/{id}','datapelangganController@destroy')->name('userdel');
    Route::get('/reset/{id}','datapelangganController@resetpass')->name('resetpass');
});

app/Http/Controllers/datapelangganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;


class datapelangganController extends Controller
{
    public function index(){
        $data_pelanggan = DB::table('data_pelanggan')->orderBy('name','ASC')->get();
        return view('lab_kimia.data_pelanggan.index',['data_pelanggan' => $data_pelanggan]);
        
    }

    public function create(){
         return view('lab_kimia.data_pelanggan.tambah');
        
    }
    public function hapus(Request $request){
        // return $request;
        //untuk script hapus
        // DB::table('jenis_program')->where('id',$request->id)->delete();
        // return redirect()->route('lab_kimia-index-jenis-program')->with('Jenis program dihapus');
    }

    public function store(Request $request){
        $data_insert[] = array(
            'name' => $request->name,
            'tlp' => $request->tlp,
            'alamat' => $request->alamat,
            'email' => $request->email,
        );

        DB::table('data_pelanggan')->insert( $data_insert);
        return Redirect()->route('datapelanggan.index') -> with('success','berhasil menambah data');
    }

    public function update(Request $request,  $id)
    {
        // dd($request->all(), $id);
        DB::table('data_pelanggan')
              ->where('id', $id)
              ->update(['name' => $request->name]);

        return redirect()->route('datapelanggan.index')
                        ->with('success','Data berhasil di update');
    }

    public function edit($id)
    {
        $data_pelanggan = DB::table('data_pelanggan')->where('id',$id)->orderBy('name','ASC')->get();
        return view('lab_kimia.data_pelanggan.edit',['data_pelanggan' => $data_pelanggan]);
    }

    public function destroy($id)

    {
        // dd($id);
        
        DB::table('users')->where('id','=', $id)->delete();
        
        return redirect()->route('lihat-user') -> with('deleted','berhasil menghapus');
    }
}

resources/views/lab_kimia/data_pelanggan/edit.blade.php
@extends('layouts.master')
@section('title', 'Data Pelanggan')

@section('content')
    <section class="section">
        <div class="section-header">
        
        <h1>Silahkan ubah dan klik simpan atau <a href="{{  route('datapelanggan.index')}}" class="btn btn-info">Kembali</a> </h1> 
        </div>
    </section>
    <div class="section-body">
        
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    @if ($message = Session::get('success'))

                    <div class="alert alert-success">
            
                        <p>{{ $message }}</p>
            
                    </div>
            
                    @endif
                    @foreach ($data_pelanggan  as $no => $item)
                        <form action="{{ route('datapelanggan.update',$item->id) }}" method="POST">
                        @method('PUT')
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>* Nama</label>
                                    <input type="text" value="{{$item->name}}" placeholder="Masukan Nama Lengkap" name="name" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>* Alamat</label>
                                        <input type="text"  value="{{$item->alamat}}" placeholder="Masukan Alamat Lengkap" name="alamat" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>* No. Tlp / Handphone</label>
                                        <input type="number"  value="{{$item->tlp}}" placeholder="Masukan no tlp yang bisa dihubungi" name="tlp" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email"  value="{{$item->email}}" placeholder="Masukan Nama Lengkap" name="email" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="card-footer text-right">
                                        <button class="btn btn-primary mr-1" type="submit">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @csrf
                        <button type="submit" class="btn btn-success">Simpan</button>
                        </form>
                    @endforeach
            </div>

        </div>
    </div>
    </div>
@endsection

@push('page-script')

@endpush

resources/views/lab_kimia/data_pelanggan/index.blade.php
@extends('layouts.master')
@section('title', 'Data Pelanggan')

@section('content')
    <section class="section">
        <div class="section-header">
        
        <h1><a href="{{ route('datapelanggan.create') }}" class="btn btn-info">Tambah Data</a>    Data Pelanggan </h1> 
        </div>
    </section>
    <div class="section-body">
        
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                    @endif
                    @if ($message = Session::get('deleted'))
                    <div class="alert alert-danger">
                        <p>{{ $message }}</p>
                    </div>
                    @endif
                    @foreach ($data_pelanggan  as $no => $item)
                        {{$no+1  }} . {{$item->name}}<br>
                        <form action="{{ route('datapelanggan.destroy',$item->id) }}" method="POST">
                            {{-- <a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a> --}}
                            <a class="btn btn-primary" href="{{ route('datapelanggan.edit',$item->id) }}">Show</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    @endforeach
            </div>

        </div>
    </div>
    </div>
@endsection

@push('page-script')

@endpush

resources/views/lab_kimia/data_pelanggan/tambah.blade.php
@extends('layouts.master')
@section('title', 'Data Pelanggan')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Input Data Pelanggan</h1>
        </div>
    </section>
    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">

                    <form action="{{ route('datapelanggan.store') }}" method="POST">
                        @csrf
                        
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>* Nama</label>
                                        <input type="text" placeholder="Masukan Nama Lengkap" name="name" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>* Alamat</label>
                                        <input type="text" placeholder="Masukan Alamat Lengkap" name="alamat" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>* No. Tlp / Handphone</label>
                                        <input type="number" placeholder="Masukan no tlp yang bisa dihubungi" name="tlp" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" placeholder="Masukan Nama Lengkap" name="email" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="card-footer text-right">
                                        <button class="btn btn-primary mr-1" type="submit">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                
                </form>
            </div>

        </div>
    </div>
    </div>
@endsection

@push('page-script')

@endpush